name: lint check

on:
  push:
    paths: "*.py"

jobs:
  codes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7.0.0

      # - name: python install
      #   uses: actions
